"""empty message

Revision ID: 89c635a8ca98
Revises: 678cdcbfe5a4
Create Date: 2017-12-11 21:33:46.394610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89c635a8ca98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructors',
    sa.Column('ssn', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('office', sa.String(length=60), nullable=True),
    sa.Column('office_hrs', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('ssn')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('teams',
    sa.Column('pro_id', sa.Integer(), nullable=False),
    sa.Column('course_no', sa.Integer(), nullable=True),
    sa.Column('team_no', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('pro_id')
    )
    op.create_index(op.f('ix_teams_title'), 'teams', ['title'], unique=False)
    op.create_table('appointments',
    sa.Column('pro_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=60), nullable=False),
    sa.Column('ins_ssn', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['ins_ssn'], ['instructors.ssn'], ),
    sa.ForeignKeyConstraint(['pro_id'], ['teams.pro_id'], ),
    sa.PrimaryKeyConstraint('pro_id', 'time')
    )
    op.create_table('milestones',
    sa.Column('pro_id', sa.Integer(), nullable=False),
    sa.Column('mil_no', sa.Integer(), nullable=False),
    sa.Column('pro_title', sa.String(length=60), nullable=True),
    sa.Column('ins_ssn', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=60), nullable=True),
    sa.Column('grade', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['ins_ssn'], ['instructors.ssn'], ),
    sa.ForeignKeyConstraint(['pro_id'], ['teams.pro_id'], ),
    sa.PrimaryKeyConstraint('pro_id', 'mil_no')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_index(op.f('ix_students_name'), 'students', ['name'], unique=False)
    op.create_index(op.f('ix_students_username'), 'students', ['username'], unique=True)
    op.create_table('participations',
    sa.Column('stu_id', sa.Integer(), nullable=False),
    sa.Column('pro_id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=1024), nullable=True),
    sa.Column('progress', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['pro_id'], ['teams.pro_id'], ),
    sa.ForeignKeyConstraint(['stu_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('stu_id', 'pro_id')
    )
    op.create_index(op.f('ix_participations_progress'), 'participations', ['progress'], unique=False)
    op.create_index(op.f('ix_participations_task'), 'participations', ['task'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_participations_task'), table_name='participations')
    op.drop_index(op.f('ix_participations_progress'), table_name='participations')
    op.drop_table('participations')
    op.drop_index(op.f('ix_students_username'), table_name='students')
    op.drop_index(op.f('ix_students_name'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_table('students')
    op.drop_table('milestones')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_teams_title'), table_name='teams')
    op.drop_table('teams')
    op.drop_table('roles')
    op.drop_table('instructors')
    # ### end Alembic commands ###
